### ISSUE TITLE
Wrong in docs

### ISSUE THREAD

**Issue by jisuo** [rannie-peralta/angularjs-store#23]
https://angularjs-store.gitbook.io/docs/tutorials/update-the-state

Should it not be:

`return { count: currentState.count + 1 };`

and 

`return { count: currentState.count - 1 };` 

?

```import { CounterState, CounterStore } from 'counter-store';

function YourController(counterStore: CounterStore) {
  counterStore.dispatch('INCREMENT_COUNT', (currentState) => {
    return { count: currentState + 1 };
  });

  counterStore.dispatch('DECREMENT_COUNT', (currentState) => {
    return { count: currentState - 1 };
  });
}

angular
  .module('App', [])
  .controller('YourController', YourController);```

**Comment by rannie-peralta** [comment]
Well, you have eyes like an eagle. You're right @jisuo . Thank you for submitting the issue. Updating the docs now.

**Comment by rannie-peralta** [comment]
https://angularjs-store.gitbook.io/docs/tutorials/update-the-state
